services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: desbravadores-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1qu~EQFWsV6VpAY!eigC"
      MSSQL_MEMORY_LIMIT_MB: 3000 
    ports:
      - "1433:1433"
    volumes:
      - desbravadores_sql_data:/var/opt/mssql

  projeto.desbravadores.api:
    build:
      context: ./
      dockerfile: ./projeto.desbravadores.Api/Dockerfile
    ports:
      - "8081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=DesbravadoresDb;User Id=sa;Password=1qu~EQFWsV6VpAY!eigC;TrustServerCertificate=True;"
      Jwt__Issuer: "projeto.desbravadores"
      Jwt__Audience: "projeto.desbravadores"
      Jwt__SigningKey: "zP9fW2kM5vX8bL0nJ3hQ6rT1yU4iA7sD9gH2jK5mN8qB0vC3xZ6pY9rS2tW5v8y!"
    depends_on:
      - sqlserver

volumes:
  desbravadores_sql_data: